estados = {
    'acre': 'AC',
    'alagoas': 'AL',
    'amazonas': 'AM',
    'amapá': 'AP',
    'bahia': 'BA',
    'ceará': 'CE',
    'distrito federal': 'DF',
    'espírito santo': 'ES',
    'goiás': 'GO',
    'maranhão': 'MA',
    'minas gerais': 'MG',
    'mato grosso': 'MT',
    'mato grosso do sul': 'MS',
    'pará': 'PA',
    'paraíba': 'PB',
    'pernambuco': 'PE',
    'piauí': 'PI',
    'paraná': 'PR',
    'rio de janeiro': 'RJ',
    'rio grande do norte': 'RN',
    'rio grande do sul': 'RS',
    'rondônia': 'RO',
    'roraima': 'RR',
    'santa catarina': 'SC',
    'são paulo': 'SP',
    'sergipe': 'SE',
    'tocantins': 'TO'
}

especialidades = {
    'acupuntura': '66',
    'administração em saúde': '97',
    'administração hospitalar': '1',
    'alergia e imunologia': '2',
    'alergia e imunopatologia': '98',
    'anatomia patológica': '84',
    'anestesiologia': '3',
    'angiologia': '4',
    'angiologia e cirurgia vascular': '67',
    'broncoesofagologia': '5',
    'cancerologia': '6',
    'cancerologia/cancerologia cirúrgica': '80',
    'cancerologia/cancerologia pediátrica': '81',
    'cardiologia': '7',
    'cirurgia cardiovascular': '8',
    'cirurgia da mão': '10',
    'cirurgia de cabeça e pescoço': '9',
    'cirurgia digestiva': '99',
    'cirurgia do aparelho digestivo': '11',
    'cirurgia do trauma': '85',
    'cirurgia gastroenterológica': '86',
    'cirurgia geral': '12',
    'cirurgia oncológica': '87',
    'cirurgia pediátrica': '13',
    'cirurgia plástica': '14',
    'cirurgia torácica': '15',
    'cirurgia vascular': '16',
    'cirurgia vascular periférica': '88',
    'citopatologia': '17',
    'clínica médica': '68',
    'coloproctologia': '69',
    'densitometria óssea': '260',
    'dermatologia': '18',
    'diagnóstico por imagem': '83',
    'doenças infecciosas e parasitárias': '89',
    'eletroencefalografia': '19',
    'endocrinologia': '70',
    'endocrinologia e metabologia': '20',
    'endoscopia': '82',
    'endoscopia digestiva': '21',
    'endoscopia peroral': '109',
    'endoscopia peroral vias aéreas': '101',
    'fisiatria': '22',
    'foniatria': '23',
    'gastroenterologia': '24',
    'genética clínica': '25',
    'genética laboratorial': '108',
    'genética médica': '71',
    'geriatria': '26',
    'geriatria e gerontologia': '90',
    'ginecologia': '27',
    'ginecologia e obstetrícia': '72',
    'hansenologia': '28',
    'hematologia': '29',
    'hematologia e hemoterapia': '73',
    'hemoterapia': '30',
    'hepatologia': '102',
    'homeopatia': '31',
    'imunologia clínica': '91',
    'infectologia': '32',
    'informática médica': '92',
    'mastologia': '33',
    'medicina de emergência': '261',
    'medicina de família e comunidade': '74',
    'medicina do adolescente': '93',
    'medicina do esporte': '103',
    'medicina do trabalho': '34',
    'medicina do tráfego': '35',
    'medicina esportiva': '36',
    'medicina física e reabilitação': '75',
    'medicina geral comunitária': '37',
    'medicina intensiva': '38',
    'medicina interna ou clínica médica': '39',
    'medicina legal': '40',
    'medicina legal e perícia médica': '259',
    'medicina nuclear': '41',
    'medicina preventiva e social': '76',
    'medicina sanitária': '42',
    'nefrologia': '43',
    'neurocirurgia': '44',
    'neurofisiologia clínica': '45',
    'neurologia': '46',
    'neurologia pediátrica': '47',
    'neuropediatria': '94',
    'nutrição parenteral e enteral': '104',
    'nutrologia': '48',
    'obstetrícia': '49',
    'oftalmologia': '50',
    'oncologia': '95',
    'oncologia clínica': '79',
    'ortopedia e traumatologia': '51',
    'otorrinolaringologia': '52',
    'patologia': '53',
    'patologia clínica': '54',
    'patologia clínica/medicina laboratorial': '77',
    'pediatria': '55',
    'pneumologia': '56',
    'pneumologia e tisiologia': '105',
    'proctologia': '57',
    'psiquiatria': '58',
    'psiquiatria infantil': '96',
    'radiodiagnóstico': '106',
    'radiologia': '59',
    'radiologia e diagnóstico por imagem': '78',
    'radioterapia': '60',
    'reumatologia': '61',
    'sexologia': '62',
    'terapia intensiva': '63',
    'terapia intensiva pediátrica': '257',
    'tisiologia': '64',
    'toco-ginecologia': '258',
    'ultrassonografia': '107',
    'ultrassonografia em ginecologia e obstetrícia': '256',
    'ultrassonografia geral': '255',
    'urologia': '65'
}

inscrições = {'principal': 'P', 'secundária': 'S', 'provisória': 'V'}

situações = {'ativo': 'A', 'inativo': 'I'}

usuário = '--user-agent="Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Microsoft; Lumia 640 XL LTE) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Mobile Safari/537.36 Edge/12.10166"'